### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by stevenjoezhang** [flatiron/union#68]
```
% node --trace-deprecation /usr/local/bin/http-server
Starting up http-server, serving ./public
Available on:
  http://127.0.0.1:8080
  http://10.2.198.96:8080
Hit CTRL-C to stop the server
[2020-11-11T03:40:13.184Z]  "GET /" "Mozilla/5.0"
(node:13803) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at new module.exports (/usr/local/lib/node_modules/http-server/node_modules/union/lib/response-stream.js:50:60)
    at new module.exports (/usr/local/lib/node_modules/http-server/node_modules/union/lib/routing-stream.js:30:17)
    at Server.requestHandler (/usr/local/lib/node_modules/http-server/node_modules/union/lib/core.js:27:25)
    at Server.emit (node:events:327:20)
    at parserOnIncoming (node:_http_server:919:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
```

https://github.com/flatiron/union/blob/b69c2c0eb95d48b49e72182e53c1788efa195cc0/lib/response-stream.js#L50

**Comment by lamweili** [comment]
See #77 instead.

**Comment by lamweili** [comment]
This has been superseded by PR #64.

Ping @indexzero @jcrugzz
